// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6
// Source: meta_land_worker.proto

package server

import (
	"context"

	"metaLand/app/worker/internal/logic"
	"metaLand/app/worker/internal/svc"
	"metaLand/app/worker/pb"
)

type MetaLandWorkerServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedMetaLandWorkerServer
}

func NewMetaLandWorkerServer(svcCtx *svc.ServiceContext) *MetaLandWorkerServer {
	return &MetaLandWorkerServer{
		svcCtx: svcCtx,
	}
}

func (s *MetaLandWorkerServer) TriggerUCETask(ctx context.Context, in *pb.TriggerUCETaskRequest) (*pb.TriggerUCETaskResponse, error) {
	l := logic.NewTriggerUCETaskLogic(ctx, s.svcCtx)
	return l.TriggerUCETask(in)
}

func (s *MetaLandWorkerServer) GetUCESchemas(ctx context.Context, in *pb.GetUCESchemasRequest) (*pb.GetUCESchemasResponse, error) {
	l := logic.NewGetUCESchemasLogic(ctx, s.svcCtx)
	return l.GetUCESchemas(in)
}

func (s *MetaLandWorkerServer) PreTestRule(ctx context.Context, in *pb.PreTestRuleRequest) (*pb.PreTestRuleResponse, error) {
	l := logic.NewPreTestRuleLogic(ctx, s.svcCtx)
	return l.PreTestRule(in)
}

func (s *MetaLandWorkerServer) SyncWeworkContact(ctx context.Context, in *pb.SyncWeworkContactRequest) (*pb.SyncWeworkContactResponse, error) {
	l := logic.NewSyncWeworkContactLogic(ctx, s.svcCtx)
	return l.SyncWeworkContact(in)
}
