// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: meta_land_worker.proto

package server

import (
	"context"

	"metaLand/app/worker/internal/logic"
	"metaLand/app/worker/internal/svc"
	"metaLand/app/worker/pb"
)

type MetaLandWorkerServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedMetaLandWorkerServer
}

func NewMetaLandWorkerServer(svcCtx *svc.ServiceContext) *MetaLandWorkerServer {
	return &MetaLandWorkerServer{
		svcCtx: svcCtx,
	}
}

func (s *MetaLandWorkerServer) TriggerUCETask(ctx context.Context, in *pb.TriggerUCETaskRequest) (*pb.TriggerUCETaskResponse, error) {
	l := logic.NewTriggerUCETaskLogic(ctx, s.svcCtx)
	return l.TriggerUCETask(in)
}
