// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: pb/meta_land_worker.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TriggerUCETaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerUCETaskRequest) Reset() {
	*x = TriggerUCETaskRequest{}
	mi := &file_pb_meta_land_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerUCETaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerUCETaskRequest) ProtoMessage() {}

func (x *TriggerUCETaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_land_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerUCETaskRequest.ProtoReflect.Descriptor instead.
func (*TriggerUCETaskRequest) Descriptor() ([]byte, []int) {
	return file_pb_meta_land_worker_proto_rawDescGZIP(), []int{0}
}

func (x *TriggerUCETaskRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type TriggerUCETaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerUCETaskResponse) Reset() {
	*x = TriggerUCETaskResponse{}
	mi := &file_pb_meta_land_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerUCETaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerUCETaskResponse) ProtoMessage() {}

func (x *TriggerUCETaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_land_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerUCETaskResponse.ProtoReflect.Descriptor instead.
func (*TriggerUCETaskResponse) Descriptor() ([]byte, []int) {
	return file_pb_meta_land_worker_proto_rawDescGZIP(), []int{1}
}

func (x *TriggerUCETaskResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_pb_meta_land_worker_proto protoreflect.FileDescriptor

const file_pb_meta_land_worker_proto_rawDesc = "" +
	"\n" +
	"\x19pb/meta_land_worker.proto\x12\x02pb\")\n" +
	"\x15TriggerUCETaskRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"0\n" +
	"\x16TriggerUCETaskResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2Y\n" +
	"\x0eMetaLandWorker\x12G\n" +
	"\x0eTriggerUCETask\x12\x19.pb.TriggerUCETaskRequest\x1a\x1a.pb.TriggerUCETaskResponseB\aZ\x05../pbb\x06proto3"

var (
	file_pb_meta_land_worker_proto_rawDescOnce sync.Once
	file_pb_meta_land_worker_proto_rawDescData []byte
)

func file_pb_meta_land_worker_proto_rawDescGZIP() []byte {
	file_pb_meta_land_worker_proto_rawDescOnce.Do(func() {
		file_pb_meta_land_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_meta_land_worker_proto_rawDesc), len(file_pb_meta_land_worker_proto_rawDesc)))
	})
	return file_pb_meta_land_worker_proto_rawDescData
}

var file_pb_meta_land_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_meta_land_worker_proto_goTypes = []any{
	(*TriggerUCETaskRequest)(nil),  // 0: pb.TriggerUCETaskRequest
	(*TriggerUCETaskResponse)(nil), // 1: pb.TriggerUCETaskResponse
}
var file_pb_meta_land_worker_proto_depIdxs = []int32{
	0, // 0: pb.MetaLandWorker.TriggerUCETask:input_type -> pb.TriggerUCETaskRequest
	1, // 1: pb.MetaLandWorker.TriggerUCETask:output_type -> pb.TriggerUCETaskResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_meta_land_worker_proto_init() }
func file_pb_meta_land_worker_proto_init() {
	if File_pb_meta_land_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_meta_land_worker_proto_rawDesc), len(file_pb_meta_land_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_meta_land_worker_proto_goTypes,
		DependencyIndexes: file_pb_meta_land_worker_proto_depIdxs,
		MessageInfos:      file_pb_meta_land_worker_proto_msgTypes,
	}.Build()
	File_pb_meta_land_worker_proto = out.File
	file_pb_meta_land_worker_proto_goTypes = nil
	file_pb_meta_land_worker_proto_depIdxs = nil
}
