// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pb/meta_land_worker.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TriggerUCETaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerUCETaskRequest) Reset() {
	*x = TriggerUCETaskRequest{}
	mi := &file_pb_meta_land_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerUCETaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerUCETaskRequest) ProtoMessage() {}

func (x *TriggerUCETaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_land_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerUCETaskRequest.ProtoReflect.Descriptor instead.
func (*TriggerUCETaskRequest) Descriptor() ([]byte, []int) {
	return file_pb_meta_land_worker_proto_rawDescGZIP(), []int{0}
}

func (x *TriggerUCETaskRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type TriggerUCETaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerUCETaskResponse) Reset() {
	*x = TriggerUCETaskResponse{}
	mi := &file_pb_meta_land_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerUCETaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerUCETaskResponse) ProtoMessage() {}

func (x *TriggerUCETaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_land_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerUCETaskResponse.ProtoReflect.Descriptor instead.
func (*TriggerUCETaskResponse) Descriptor() ([]byte, []int) {
	return file_pb_meta_land_worker_proto_rawDescGZIP(), []int{1}
}

func (x *TriggerUCETaskResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UCESchemaField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Operations    []string               `protobuf:"bytes,4,rep,name=operations,proto3" json:"operations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UCESchemaField) Reset() {
	*x = UCESchemaField{}
	mi := &file_pb_meta_land_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UCESchemaField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UCESchemaField) ProtoMessage() {}

func (x *UCESchemaField) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_land_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UCESchemaField.ProtoReflect.Descriptor instead.
func (*UCESchemaField) Descriptor() ([]byte, []int) {
	return file_pb_meta_land_worker_proto_rawDescGZIP(), []int{2}
}

func (x *UCESchemaField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UCESchemaField) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *UCESchemaField) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UCESchemaField) GetOperations() []string {
	if x != nil {
		return x.Operations
	}
	return nil
}

type UCESchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Fields        []*UCESchemaField      `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UCESchema) Reset() {
	*x = UCESchema{}
	mi := &file_pb_meta_land_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UCESchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UCESchema) ProtoMessage() {}

func (x *UCESchema) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_land_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UCESchema.ProtoReflect.Descriptor instead.
func (*UCESchema) Descriptor() ([]byte, []int) {
	return file_pb_meta_land_worker_proto_rawDescGZIP(), []int{3}
}

func (x *UCESchema) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UCESchema) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *UCESchema) GetFields() []*UCESchemaField {
	if x != nil {
		return x.Fields
	}
	return nil
}

type GetUCESchemasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUCESchemasRequest) Reset() {
	*x = GetUCESchemasRequest{}
	mi := &file_pb_meta_land_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUCESchemasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUCESchemasRequest) ProtoMessage() {}

func (x *GetUCESchemasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_land_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUCESchemasRequest.ProtoReflect.Descriptor instead.
func (*GetUCESchemasRequest) Descriptor() ([]byte, []int) {
	return file_pb_meta_land_worker_proto_rawDescGZIP(), []int{4}
}

type GetUCESchemasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schemas       []*UCESchema           `protobuf:"bytes,1,rep,name=schemas,proto3" json:"schemas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUCESchemasResponse) Reset() {
	*x = GetUCESchemasResponse{}
	mi := &file_pb_meta_land_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUCESchemasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUCESchemasResponse) ProtoMessage() {}

func (x *GetUCESchemasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_land_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUCESchemasResponse.ProtoReflect.Descriptor instead.
func (*GetUCESchemasResponse) Descriptor() ([]byte, []int) {
	return file_pb_meta_land_worker_proto_rawDescGZIP(), []int{5}
}

func (x *GetUCESchemasResponse) GetSchemas() []*UCESchema {
	if x != nil {
		return x.Schemas
	}
	return nil
}

type PreTestRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *structpb.Struct       `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreTestRuleRequest) Reset() {
	*x = PreTestRuleRequest{}
	mi := &file_pb_meta_land_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreTestRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreTestRuleRequest) ProtoMessage() {}

func (x *PreTestRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_land_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreTestRuleRequest.ProtoReflect.Descriptor instead.
func (*PreTestRuleRequest) Descriptor() ([]byte, []int) {
	return file_pb_meta_land_worker_proto_rawDescGZIP(), []int{6}
}

func (x *PreTestRuleRequest) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type PreTestRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreTestRuleResponse) Reset() {
	*x = PreTestRuleResponse{}
	mi := &file_pb_meta_land_worker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreTestRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreTestRuleResponse) ProtoMessage() {}

func (x *PreTestRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_land_worker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreTestRuleResponse.ProtoReflect.Descriptor instead.
func (*PreTestRuleResponse) Descriptor() ([]byte, []int) {
	return file_pb_meta_land_worker_proto_rawDescGZIP(), []int{7}
}

func (x *PreTestRuleResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PreTestRuleResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type SyncWeworkContactRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UnionId        string                 `protobuf:"bytes,1,opt,name=unionId,proto3" json:"unionId,omitempty"`
	ExternalUserId string                 `protobuf:"bytes,2,opt,name=externalUserId,proto3" json:"externalUserId,omitempty"`
	SocialAppId    int64                  `protobuf:"varint,3,opt,name=socialAppId,proto3" json:"socialAppId,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncWeworkContactRequest) Reset() {
	*x = SyncWeworkContactRequest{}
	mi := &file_pb_meta_land_worker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncWeworkContactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncWeworkContactRequest) ProtoMessage() {}

func (x *SyncWeworkContactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_land_worker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncWeworkContactRequest.ProtoReflect.Descriptor instead.
func (*SyncWeworkContactRequest) Descriptor() ([]byte, []int) {
	return file_pb_meta_land_worker_proto_rawDescGZIP(), []int{8}
}

func (x *SyncWeworkContactRequest) GetUnionId() string {
	if x != nil {
		return x.UnionId
	}
	return ""
}

func (x *SyncWeworkContactRequest) GetExternalUserId() string {
	if x != nil {
		return x.ExternalUserId
	}
	return ""
}

func (x *SyncWeworkContactRequest) GetSocialAppId() int64 {
	if x != nil {
		return x.SocialAppId
	}
	return 0
}

type SyncWeworkContactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncWeworkContactResponse) Reset() {
	*x = SyncWeworkContactResponse{}
	mi := &file_pb_meta_land_worker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncWeworkContactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncWeworkContactResponse) ProtoMessage() {}

func (x *SyncWeworkContactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_land_worker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncWeworkContactResponse.ProtoReflect.Descriptor instead.
func (*SyncWeworkContactResponse) Descriptor() ([]byte, []int) {
	return file_pb_meta_land_worker_proto_rawDescGZIP(), []int{9}
}

func (x *SyncWeworkContactResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_pb_meta_land_worker_proto protoreflect.FileDescriptor

const file_pb_meta_land_worker_proto_rawDesc = "" +
	"\n" +
	"\x19pb/meta_land_worker.proto\x12\x02pb\x1a\x1cgoogle/protobuf/struct.proto\")\n" +
	"\x15TriggerUCETaskRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"0\n" +
	"\x16TriggerUCETaskResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"n\n" +
	"\x0eUCESchemaField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1e\n" +
	"\n" +
	"operations\x18\x04 \x03(\tR\n" +
	"operations\"a\n" +
	"\tUCESchema\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12*\n" +
	"\x06fields\x18\x03 \x03(\v2\x12.pb.UCESchemaFieldR\x06fields\"\x16\n" +
	"\x14GetUCESchemasRequest\"@\n" +
	"\x15GetUCESchemasResponse\x12'\n" +
	"\aschemas\x18\x01 \x03(\v2\r.pb.UCESchemaR\aschemas\"A\n" +
	"\x12PreTestRuleRequest\x12+\n" +
	"\x04data\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x04data\"C\n" +
	"\x13PreTestRuleResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"~\n" +
	"\x18SyncWeworkContactRequest\x12\x18\n" +
	"\aunionId\x18\x01 \x01(\tR\aunionId\x12&\n" +
	"\x0eexternalUserId\x18\x02 \x01(\tR\x0eexternalUserId\x12 \n" +
	"\vsocialAppId\x18\x03 \x01(\x03R\vsocialAppId\"3\n" +
	"\x19SyncWeworkContactResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xb1\x02\n" +
	"\x0eMetaLandWorker\x12G\n" +
	"\x0eTriggerUCETask\x12\x19.pb.TriggerUCETaskRequest\x1a\x1a.pb.TriggerUCETaskResponse\x12D\n" +
	"\rGetUCESchemas\x12\x18.pb.GetUCESchemasRequest\x1a\x19.pb.GetUCESchemasResponse\x12>\n" +
	"\vPreTestRule\x12\x16.pb.PreTestRuleRequest\x1a\x17.pb.PreTestRuleResponse\x12P\n" +
	"\x11SyncWeworkContact\x12\x1c.pb.SyncWeworkContactRequest\x1a\x1d.pb.SyncWeworkContactResponseB\aZ\x05../pbb\x06proto3"

var (
	file_pb_meta_land_worker_proto_rawDescOnce sync.Once
	file_pb_meta_land_worker_proto_rawDescData []byte
)

func file_pb_meta_land_worker_proto_rawDescGZIP() []byte {
	file_pb_meta_land_worker_proto_rawDescOnce.Do(func() {
		file_pb_meta_land_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_meta_land_worker_proto_rawDesc), len(file_pb_meta_land_worker_proto_rawDesc)))
	})
	return file_pb_meta_land_worker_proto_rawDescData
}

var file_pb_meta_land_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pb_meta_land_worker_proto_goTypes = []any{
	(*TriggerUCETaskRequest)(nil),     // 0: pb.TriggerUCETaskRequest
	(*TriggerUCETaskResponse)(nil),    // 1: pb.TriggerUCETaskResponse
	(*UCESchemaField)(nil),            // 2: pb.UCESchemaField
	(*UCESchema)(nil),                 // 3: pb.UCESchema
	(*GetUCESchemasRequest)(nil),      // 4: pb.GetUCESchemasRequest
	(*GetUCESchemasResponse)(nil),     // 5: pb.GetUCESchemasResponse
	(*PreTestRuleRequest)(nil),        // 6: pb.PreTestRuleRequest
	(*PreTestRuleResponse)(nil),       // 7: pb.PreTestRuleResponse
	(*SyncWeworkContactRequest)(nil),  // 8: pb.SyncWeworkContactRequest
	(*SyncWeworkContactResponse)(nil), // 9: pb.SyncWeworkContactResponse
	(*structpb.Struct)(nil),           // 10: google.protobuf.Struct
}
var file_pb_meta_land_worker_proto_depIdxs = []int32{
	2,  // 0: pb.UCESchema.fields:type_name -> pb.UCESchemaField
	3,  // 1: pb.GetUCESchemasResponse.schemas:type_name -> pb.UCESchema
	10, // 2: pb.PreTestRuleRequest.data:type_name -> google.protobuf.Struct
	0,  // 3: pb.MetaLandWorker.TriggerUCETask:input_type -> pb.TriggerUCETaskRequest
	4,  // 4: pb.MetaLandWorker.GetUCESchemas:input_type -> pb.GetUCESchemasRequest
	6,  // 5: pb.MetaLandWorker.PreTestRule:input_type -> pb.PreTestRuleRequest
	8,  // 6: pb.MetaLandWorker.SyncWeworkContact:input_type -> pb.SyncWeworkContactRequest
	1,  // 7: pb.MetaLandWorker.TriggerUCETask:output_type -> pb.TriggerUCETaskResponse
	5,  // 8: pb.MetaLandWorker.GetUCESchemas:output_type -> pb.GetUCESchemasResponse
	7,  // 9: pb.MetaLandWorker.PreTestRule:output_type -> pb.PreTestRuleResponse
	9,  // 10: pb.MetaLandWorker.SyncWeworkContact:output_type -> pb.SyncWeworkContactResponse
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_pb_meta_land_worker_proto_init() }
func file_pb_meta_land_worker_proto_init() {
	if File_pb_meta_land_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_meta_land_worker_proto_rawDesc), len(file_pb_meta_land_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_meta_land_worker_proto_goTypes,
		DependencyIndexes: file_pb_meta_land_worker_proto_depIdxs,
		MessageInfos:      file_pb_meta_land_worker_proto_msgTypes,
	}.Build()
	File_pb_meta_land_worker_proto = out.File
	file_pb_meta_land_worker_proto_goTypes = nil
	file_pb_meta_land_worker_proto_depIdxs = nil
}
