// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	comerFollowRelFieldNames          = builder.RawFieldNames(&ComerFollowRel{})
	comerFollowRelRows                = strings.Join(comerFollowRelFieldNames, ",")
	comerFollowRelRowsExpectAutoSet   = strings.Join(stringx.Remove(comerFollowRelFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	comerFollowRelRowsWithPlaceHolder = strings.Join(stringx.Remove(comerFollowRelFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	comerFollowRelModel interface {
		Insert(ctx context.Context, data *ComerFollowRel) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ComerFollowRel, error)
		Update(ctx context.Context, data *ComerFollowRel) error
		Delete(ctx context.Context, id int64) error
	}

	defaultComerFollowRelModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ComerFollowRel struct {
		Id            int64     `db:"id"`
		ComerId       int64     `db:"comer_id"`
		TargetComerId int64     `db:"target_comer_id"`
		CreatedAt     time.Time `db:"created_at"`
		UpdatedAt     time.Time `db:"updated_at"`
		IsDeleted     int64     `db:"is_deleted"`
	}
)

func newComerFollowRelModel(conn sqlx.SqlConn) *defaultComerFollowRelModel {
	return &defaultComerFollowRelModel{
		conn:  conn,
		table: "`comer_follow_rel`",
	}
}

func (m *defaultComerFollowRelModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultComerFollowRelModel) FindOne(ctx context.Context, id int64) (*ComerFollowRel, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", comerFollowRelRows, m.table)
	var resp ComerFollowRel
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultComerFollowRelModel) Insert(ctx context.Context, data *ComerFollowRel) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, comerFollowRelRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ComerId, data.TargetComerId, data.IsDeleted)
	return ret, err
}

func (m *defaultComerFollowRelModel) Update(ctx context.Context, data *ComerFollowRel) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, comerFollowRelRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ComerId, data.TargetComerId, data.IsDeleted, data.Id)
	return err
}

func (m *defaultComerFollowRelModel) tableName() string {
	return m.table
}
