// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	governanceChoiceFieldNames          = builder.RawFieldNames(&GovernanceChoice{})
	governanceChoiceRows                = strings.Join(governanceChoiceFieldNames, ",")
	governanceChoiceRowsExpectAutoSet   = strings.Join(stringx.Remove(governanceChoiceFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	governanceChoiceRowsWithPlaceHolder = strings.Join(stringx.Remove(governanceChoiceFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	governanceChoiceModel interface {
		Insert(ctx context.Context, data *GovernanceChoice) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*GovernanceChoice, error)
		Update(ctx context.Context, data *GovernanceChoice) error
		Delete(ctx context.Context, id int64) error
	}

	defaultGovernanceChoiceModel struct {
		conn  sqlx.SqlConn
		table string
	}

	GovernanceChoice struct {
		Id         int64          `db:"id"`
		ProposalId sql.NullInt64  `db:"proposal_id"`
		ItemName   sql.NullString `db:"item_name"`
		SeqNum     sql.NullInt64  `db:"seq_num"`
		CreatedAt  sql.NullTime   `db:"created_at"`
		UpdatedAt  sql.NullTime   `db:"updated_at"`
		IsDeleted  sql.NullInt64  `db:"is_deleted"`
	}
)

func newGovernanceChoiceModel(conn sqlx.SqlConn) *defaultGovernanceChoiceModel {
	return &defaultGovernanceChoiceModel{
		conn:  conn,
		table: "`governance_choice`",
	}
}

func (m *defaultGovernanceChoiceModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultGovernanceChoiceModel) FindOne(ctx context.Context, id int64) (*GovernanceChoice, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", governanceChoiceRows, m.table)
	var resp GovernanceChoice
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGovernanceChoiceModel) Insert(ctx context.Context, data *GovernanceChoice) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, governanceChoiceRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.ProposalId, data.ItemName, data.SeqNum, data.IsDeleted)
	return ret, err
}

func (m *defaultGovernanceChoiceModel) Update(ctx context.Context, data *GovernanceChoice) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, governanceChoiceRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ProposalId, data.ItemName, data.SeqNum, data.IsDeleted, data.Id)
	return err
}

func (m *defaultGovernanceChoiceModel) tableName() string {
	return m.table
}
