// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	postUpdateFieldNames          = builder.RawFieldNames(&PostUpdate{})
	postUpdateRows                = strings.Join(postUpdateFieldNames, ",")
	postUpdateRowsExpectAutoSet   = strings.Join(stringx.Remove(postUpdateFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	postUpdateRowsWithPlaceHolder = strings.Join(stringx.Remove(postUpdateFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	postUpdateModel interface {
		Insert(ctx context.Context, data *PostUpdate) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*PostUpdate, error)
		Update(ctx context.Context, data *PostUpdate) error
		Delete(ctx context.Context, id int64) error
	}

	defaultPostUpdateModel struct {
		conn  sqlx.SqlConn
		table string
	}

	PostUpdate struct {
		Id         int64          `db:"id"`
		SourceType sql.NullInt64  `db:"source_type"`
		SourceId   sql.NullInt64  `db:"source_id"`
		ComerId    sql.NullInt64  `db:"comer_id"`
		Content    sql.NullString `db:"content"`
		Timestamp  sql.NullTime   `db:"timestamp"`
		CreatedAt  sql.NullTime   `db:"created_at"`
		UpdatedAt  sql.NullTime   `db:"updated_at"`
		IsDeleted  sql.NullInt64  `db:"is_deleted"`
	}
)

func newPostUpdateModel(conn sqlx.SqlConn) *defaultPostUpdateModel {
	return &defaultPostUpdateModel{
		conn:  conn,
		table: "`post_update`",
	}
}

func (m *defaultPostUpdateModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultPostUpdateModel) FindOne(ctx context.Context, id int64) (*PostUpdate, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", postUpdateRows, m.table)
	var resp PostUpdate
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPostUpdateModel) Insert(ctx context.Context, data *PostUpdate) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, postUpdateRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.SourceType, data.SourceId, data.ComerId, data.Content, data.Timestamp, data.IsDeleted)
	return ret, err
}

func (m *defaultPostUpdateModel) Update(ctx context.Context, data *PostUpdate) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, postUpdateRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.SourceType, data.SourceId, data.ComerId, data.Content, data.Timestamp, data.IsDeleted, data.Id)
	return err
}

func (m *defaultPostUpdateModel) tableName() string {
	return m.table
}
