// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	startupGroupMemberRelFieldNames          = builder.RawFieldNames(&StartupGroupMemberRel{})
	startupGroupMemberRelRows                = strings.Join(startupGroupMemberRelFieldNames, ",")
	startupGroupMemberRelRowsExpectAutoSet   = strings.Join(stringx.Remove(startupGroupMemberRelFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	startupGroupMemberRelRowsWithPlaceHolder = strings.Join(stringx.Remove(startupGroupMemberRelFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	startupGroupMemberRelModel interface {
		Insert(ctx context.Context, data *StartupGroupMemberRel) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*StartupGroupMemberRel, error)
		FindOneByComerIdGroupId(ctx context.Context, comerId int64, groupId int64) (*StartupGroupMemberRel, error)
		Update(ctx context.Context, data *StartupGroupMemberRel) error
		Delete(ctx context.Context, id int64) error
	}

	defaultStartupGroupMemberRelModel struct {
		conn  sqlx.SqlConn
		table string
	}

	StartupGroupMemberRel struct {
		Id        int64     `db:"id"`
		ComerId   int64     `db:"comer_id"`   // comer_id
		StartupId int64     `db:"startup_id"` // startup_id
		GroupId   int64     `db:"group_id"`   // group id
		CreatedAt time.Time `db:"created_at"`
		UpdatedAt time.Time `db:"updated_at"`
	}
)

func newStartupGroupMemberRelModel(conn sqlx.SqlConn) *defaultStartupGroupMemberRelModel {
	return &defaultStartupGroupMemberRelModel{
		conn:  conn,
		table: "`startup_group_member_rel`",
	}
}

func (m *defaultStartupGroupMemberRelModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultStartupGroupMemberRelModel) FindOne(ctx context.Context, id int64) (*StartupGroupMemberRel, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", startupGroupMemberRelRows, m.table)
	var resp StartupGroupMemberRel
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultStartupGroupMemberRelModel) FindOneByComerIdGroupId(ctx context.Context, comerId int64, groupId int64) (*StartupGroupMemberRel, error) {
	var resp StartupGroupMemberRel
	query := fmt.Sprintf("select %s from %s where `comer_id` = ? and `group_id` = ? limit 1", startupGroupMemberRelRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, comerId, groupId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultStartupGroupMemberRelModel) Insert(ctx context.Context, data *StartupGroupMemberRel) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, startupGroupMemberRelRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.ComerId, data.StartupId, data.GroupId)
	return ret, err
}

func (m *defaultStartupGroupMemberRelModel) Update(ctx context.Context, newData *StartupGroupMemberRel) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, startupGroupMemberRelRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.ComerId, newData.StartupId, newData.GroupId, newData.Id)
	return err
}

func (m *defaultStartupGroupMemberRelModel) tableName() string {
	return m.table
}
