// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	startupFollowRelFieldNames          = builder.RawFieldNames(&StartupFollowRel{})
	startupFollowRelRows                = strings.Join(startupFollowRelFieldNames, ",")
	startupFollowRelRowsExpectAutoSet   = strings.Join(stringx.Remove(startupFollowRelFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	startupFollowRelRowsWithPlaceHolder = strings.Join(stringx.Remove(startupFollowRelFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	startupFollowRelModel interface {
		Insert(ctx context.Context, data *StartupFollowRel) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*StartupFollowRel, error)
		FindOneByComerIdStartupId(ctx context.Context, comerId int64, startupId int64) (*StartupFollowRel, error)
		Update(ctx context.Context, data *StartupFollowRel) error
		Delete(ctx context.Context, id int64) error
	}

	defaultStartupFollowRelModel struct {
		conn  sqlx.SqlConn
		table string
	}

	StartupFollowRel struct {
		Id        int64     `db:"id"`
		ComerId   int64     `db:"comer_id"`   // comer_id
		StartupId int64     `db:"startup_id"` // startup_id
		CreatedAt time.Time `db:"created_at"`
		UpdatedAt time.Time `db:"updated_at"`
	}
)

func newStartupFollowRelModel(conn sqlx.SqlConn) *defaultStartupFollowRelModel {
	return &defaultStartupFollowRelModel{
		conn:  conn,
		table: "`startup_follow_rel`",
	}
}

func (m *defaultStartupFollowRelModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultStartupFollowRelModel) FindOne(ctx context.Context, id int64) (*StartupFollowRel, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", startupFollowRelRows, m.table)
	var resp StartupFollowRel
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultStartupFollowRelModel) FindOneByComerIdStartupId(ctx context.Context, comerId int64, startupId int64) (*StartupFollowRel, error) {
	var resp StartupFollowRel
	query := fmt.Sprintf("select %s from %s where `comer_id` = ? and `startup_id` = ? limit 1", startupFollowRelRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, comerId, startupId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultStartupFollowRelModel) Insert(ctx context.Context, data *StartupFollowRel) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, startupFollowRelRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.ComerId, data.StartupId)
	return ret, err
}

func (m *defaultStartupFollowRelModel) Update(ctx context.Context, newData *StartupFollowRel) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, startupFollowRelRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.ComerId, newData.StartupId, newData.Id)
	return err
}

func (m *defaultStartupFollowRelModel) tableName() string {
	return m.table
}
