// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	startupGroupFieldNames          = builder.RawFieldNames(&StartupGroup{})
	startupGroupRows                = strings.Join(startupGroupFieldNames, ",")
	startupGroupRowsExpectAutoSet   = strings.Join(stringx.Remove(startupGroupFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	startupGroupRowsWithPlaceHolder = strings.Join(stringx.Remove(startupGroupFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	startupGroupModel interface {
		Insert(ctx context.Context, data *StartupGroup) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*StartupGroup, error)
		FindOneByNameId(ctx context.Context, name string, id int64) (*StartupGroup, error)
		Update(ctx context.Context, data *StartupGroup) error
		Delete(ctx context.Context, id int64) error
	}

	defaultStartupGroupModel struct {
		conn  sqlx.SqlConn
		table string
	}

	StartupGroup struct {
		Id        int64     `db:"id"`
		ComerId   int64     `db:"comer_id"`   // comer_id
		StartupId int64     `db:"startup_id"` // startup_id
		Name      string    `db:"name"`       // group name
		CreatedAt time.Time `db:"created_at"`
		UpdatedAt time.Time `db:"updated_at"`
	}
)

func newStartupGroupModel(conn sqlx.SqlConn) *defaultStartupGroupModel {
	return &defaultStartupGroupModel{
		conn:  conn,
		table: "`startup_group`",
	}
}

func (m *defaultStartupGroupModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultStartupGroupModel) FindOne(ctx context.Context, id int64) (*StartupGroup, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", startupGroupRows, m.table)
	var resp StartupGroup
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultStartupGroupModel) FindOneByNameId(ctx context.Context, name string, id int64) (*StartupGroup, error) {
	var resp StartupGroup
	query := fmt.Sprintf("select %s from %s where `name` = ? and `id` = ? limit 1", startupGroupRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, name, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultStartupGroupModel) Insert(ctx context.Context, data *StartupGroup) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, startupGroupRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.ComerId, data.StartupId, data.Name)
	return ret, err
}

func (m *defaultStartupGroupModel) Update(ctx context.Context, newData *StartupGroup) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, startupGroupRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.ComerId, newData.StartupId, newData.Name, newData.Id)
	return err
}

func (m *defaultStartupGroupModel) tableName() string {
	return m.table
}
