// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6

package handler

import (
	"net/http"

	metaLandstartup "metaLand/app/api/internal/handler/metaLand/startup"
	"metaLand/app/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.OIDCAuthMiddleware},
			[]rest.Route{
				{
					// 查询项目列表
					Method:  http.MethodGet,
					Path:    "/startups",
					Handler: metaLandstartup.ListStartupsHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/startup"),
	)
}
