// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type ComerLoginResponse struct {
	ComerID       uint64                     `json:"comerID"`
	Nick          string                     `json:"nick"`
	Avatar        string                     `json:"avatar"`
	Address       string                     `json:"address"`
	Token         string                     `json:"token"`
	IsProfiled    bool                       `json:"isProfiled"`
	FirstLogin    bool                       `json:"firstLogin"`
	ComerAccounts []*OauthAccountBindingInfo `json:"comerAccounts"`
}

type EthLoginRequest struct {
	Address   string `json:"address" binding:"len=42,startswith=0x"`
	Signature string `json:"signature" binding:"required"`
}

type GetNonceByAddressRequest struct {
	WalletAddress string `path:"wallet_address"`
}

type JwtAuthorizationResponse struct {
	Token string `json:"token"`
}

type WalletNonceResponse struct {
	Nonce string `json:"nonce"`
}
