// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type BountyInfoResponse struct {
	ApplicantDeposit            int                   `json:"applicant_deposit"`
	ApplicantMinDeposit         int                   `json:"applicant_min_deposit"`
	Applicants                  []BountyApplicant     `json:"applicants"`
	ApplyDeadline               string                `json:"apply_deadline"`
	BountyApplicant             BountyApplicant       `json:"bounty_applicant"`
	ChainId                     uint64                `json:"chain_id"`
	ComerId                     uint64                `json:"comer_id"`
	Contacts                    []BountyContact       `json:"contacts"`
	ContractAddress             string                `json:"contract_address"`
	CreatedAt                   string                `json:"created_at"`
	DepositContractAddress      string                `json:"deposit_contract_address"`
	DepositContractTokenDecimal int                   `json:"deposit_contract_token_decimal"`
	DepositContractTokenSymbol  string                `json:"deposit_contract_token_symbol"`
	DepositRecords              []BountyDepositRecord `json:"deposit_records"`
	Description                 string                `json:"description"`
	DiscussionLink              string                `json:"discussion_link"`
	ExpiredTime                 string                `json:"expired_time"`
	Founder                     BountyComer           `json:"founder"`
	FounderDeposit              int                   `json:"founder_deposit"`
	Id                          uint64                `json:"id"`
	IsLock                      int                   `json:"is_lock"`
	MyDeposit                   int                   `json:"my_deposit"`
	MyRole                      int                   `json:"my_role"`
	MyStatus                    int                   `json:"my_status"`
	PaymentMode                 int                   `json:"payment_mode"`
	Period                      BountyPaymentPeriod   `json:"period"`
	PostUpdates                 []PostUpdate          `json:"post_updates"`
	Skills                      []TagRelationResponse `json:"skills"`
	Startup                     StartupCardResponse   `json:"startup"`
	StartupId                   int                   `json:"startup_id"`
	Status                      int                   `json:"status"`
	Terms                       []BountyPaymentTerms  `json:"terms"`
	Title                       string                `json:"title"`
	TxHash                      string                `json:"tx_hash"`
}

type DetailRequest struct {
	Id uint64 `form:"id"`
}

type ListBountiesRequest struct {
	Limit     int    `json:"limit"`
	Offset    int    `json:"offset"`
	IsDeleted bool   `json:"is_deleted,optional"`
	Keyword   string `json:"keyword,optional"`
	Mode      uint8  `json:"mode,optional"`
}

type ListBountiesResponse struct {
	List  []*Bounty `json:list`
	Total int64     `json: total`
}
