// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type BountyInfoResponse struct {
	ApplicantDeposit            int                   `json:"applicantDeposit"`
	ApplicantMinDeposit         int                   `json:"applicantMinDeposit"`
	Applicants                  []BountyApplicant     `json:"applicants"`
	ApplyDeadline               string                `json:"applyDeadline"`
	BountyApplicant             BountyApplicant       `json:"bountyApplicant"`
	ChainId                     uint64                `json:"chainId"`
	ComerId                     uint64                `json:"comerId"`
	Contacts                    []BountyContact       `json:"contacts"`
	ContractAddress             string                `json:"contractAddress"`
	CreatedAt                   string                `json:"createdAt"`
	DepositContractAddress      string                `json:"depositContractAddress"`
	DepositContractTokenDecimal int                   `json:"depositContractTokenDecimal"`
	DepositContractTokenSymbol  string                `json:"depositContractTokenSymbol"`
	DepositRecords              []BountyDepositRecord `json:"depositRecords"`
	Description                 string                `json:"description"`
	DiscussionLink              string                `json:"discussionLink"`
	ExpiredTime                 string                `json:"expiredTime"`
	Founder                     BountyComer           `json:"founder"`
	FounderDeposit              int                   `json:"founderDeposit"`
	Id                          uint64                `json:"id"`
	IsLock                      int                   `json:"isLock"`
	MyDeposit                   int                   `json:"myDeposit"`
	MyRole                      int                   `json:"myRole"`
	MyStatus                    int                   `json:"myStatus"`
	PaymentMode                 int                   `json:"paymentMode"`
	Period                      BountyPaymentPeriod   `json:"period"`
	PostUpdates                 []PostUpdate          `json:"postUpdates"`
	Skills                      []TagRelationResponse `json:"skills"`
	Startup                     StartupCardResponse   `json:"startup"`
	StartupId                   int                   `json:"startupId"`
	Status                      int                   `json:"status"`
	Terms                       []BountyPaymentTerms  `json:"terms"`
	Title                       string                `json:"title"`
	TxHash                      string                `json:"txHash"`
}

type DetailRequest struct {
	Id uint64 `form:"id"`
}

type ListBountiesRequest struct {
	Limit     int    `json:"limit"`
	Offset    int    `json:"offset"`
	IsDeleted bool   `json:"isDeleted,optional"`
	Keyword   string `json:"keyword,optional"`
	Mode      uint8  `json:"mode,optional"`
}

type ListBountiesResponse struct {
	List  []*Bounty `json:list`
	Total int64     `json: total`
}
