// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type CreateCrowdfundingRequest struct {
	Crowdfunding
}

type CreateCrowdfundingResponse struct {
}

type GetCrowdfundingInfoRequest struct {
	CrowdfundingId uint64 `path:"crowdfunding_id"`
}

type GetCrowdfundingInfoResponse struct {
	CrowdfundingRes
	Investor
	Investors uint64 `json:"investors"`
	Startup
	Swaps []Swap `json:"swaps"`
}

type GetCrowdfundingRequest struct {
	Page    int    `form:"page"`
	Size    int    `form:"size"`
	Keyword string `form:"keyword,optional"`
}

type GetCrowdfundingResponse struct {
	Page  int               `json:"page"`
	Size  int               `json:"size"`
	Total uint64            `json:"total"`
	List  []CrowdfundingRes `json:"list"`
}

type GetCrowdfundingSwapRecordsRequest struct {
	CrowdfundingId uint64 `path:"crowdfunding_id"`
}

type GetCrowdfundingSwapRecordsResponse struct {
	List []Swap `json:"list"`
}

type GetCrowdfundingTransferLpSignRequest struct {
	CrowdfundingId uint64 `path:"crowdfunding_id"`
}

type GetCrowdfundingTransferLpSignResponse struct {
	Data string `json:"data"`
	Sign string `json:"sign"`
}

type UpdateCrowdfundingRequest struct {
	CrowdfundingId uint64 `json:"crowdfunding_id"`
	TxHash         string `json:"tx_hash""`
	SwapPercent    string `json:"swap_percent,omitempty"`
	BuyPrice       string `json:"buy_price,omitempty"`
	MaxBuyAmount   string `json:"max_buy_amount,omitempty"`
	MaxSellPercent string `json:"max_sell_percent,omitempty"`
	EndTime        string `json:"end_time,omitempty"`
}

type UpdateCrowdfundingResponse struct {
	SellInfo
	BuyInfo
}
