// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type CreateGovernanceSettingResponse struct {
}

type CreateOrUpdateGovernanceSettingRequest struct {
	StartupId string `path:"startup_Id"`
	SettingRequest
	Strategies []StrategyRequest `json:"strategies"`
	Admins     []AdminRequest    `json:"admins"`
}

type GetGovernanceSettingRequest struct {
	StartupId string `path:"startup_Id"`
}

type GetGovernanceSettingResponse struct {
	GovernanceSetting
	Strategies []GovernanceStrategy `json:"strategies"`
	Admins     []GovernanceAdmin    `json:"admins"`
}
