// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type CreateGovernanceSettingResponse struct {
	GovernanceSetting GovernanceSetting `json:"governanceSetting"`
}

type CreateOrUpdateGovernanceSettingRequest struct {
	StartupId uint64 `path:"startup_id"`
	SettingRequest
	Strategies []StrategyRequest `json:"strategies"`
	Admins     []AdminRequest    `json:"admins"`
}

type GetGovernanceSettingRequest struct {
	StartupId uint64 `path:"startup_id"`
}

type GetGovernanceSettingResponse struct {
	GovernanceSetting
	Strategies []GovernanceStrategy `json:"strategies"`
	Admins     []GovernanceAdmin    `json:"admins"`
}
