// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type LanguageResponse struct {
	Id       int    `json:"id"`
	ComerId  int    `json:"comer_id"`
	Code     string `json:"code"`
	Language string `json:"language"`
	Level    int    `json:"level"`
	IsNative bool   `json:"is_native"`
}
