// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type CreateProposalRequest struct {
	GovernanceProposal
	Choices []ProposalChoiceReq `json:"choices"`
}

type CreateProposalResponse struct {
}

type CreateVoteProposalRequest struct {
	ProposalId         uint64 `path:"proposal_id"`
	VoterWalletAddress string `json:"voter_wallet_address"`
	ChoiceItemId       uint64 `json:"choice_item_id"`
	ChoiceItemName     string `json:"choice_item_name"`
	Votes              string `json:"votes"`
	IpfsHash           string `json:"ipfs_hash"`
}

type CreateVoteProposalResponse struct {
}

type DeleteProposalRequest struct {
	ProposalId uint64 `path:"proposal_id"`
}

type DeleteProposalResponse struct {
}

type GetProposalInfoRequest struct {
	ProposalId uint64 `path:"proposal_id"`
}

type GetProposalInfoResponse struct {
	BaseInfo
	GovernanceProposal
	Choices []ProposalChoiceRes `json:"choices"`
	Comer   ComerResponse       `json:"comer"`
	Startup StartupRes          `json:"startup"`
}

type GetProposalInvestRecordsRequest struct {
	ProposalId uint64 `path:"proposal_id"`
	Page       int    `form:"page"`
	Size       int    `form:"size"`
}

type GetProposalInvestRecordsResponse struct {
	Page  int              `json:"page"`
	Size  int              `json:"size"`
	Total int64            `json:"total"`
	List  []GovernanceVote `json:"list"`
}

type GetProposalsRequest struct {
	Page    int    `form:"page"`
	Size    int    `form:"size"`
	Keyword string `form:"keyword"`
}

type GetProposalsResponse struct {
	Page  int                      `json:"page"`
	Size  int                      `json:"size"`
	Total int64                    `json:"total"`
	List  []GovernanceProposalInfo `json:"list"`
}
