// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type FollowRelation struct {
	ComerID uint64 `json:comerID`
}

type Startup struct {
	ComerID              uint64 `json:"comerID" db:"comer_id"`
	Name                 string `json:"name" db:"name"`
	Mode                 uint8  `json:"mode" db:"mode"`
	Logo                 string `json:"logo" db:"logo"`
	Cover                string `json:"cover" db:"cover"`
	Mission              string `json:"mission" db:"mission"`
	TokenContractAddress string `json:"tokenContractAddress" db:"token_contract_address"`
	Overview             string `json:"overview" db:"overview"`
	ChainID              uint64 `json:"chainID" db:"chain_id"`
	TxHash               string `json:"blockChainAddress" db:"tx_hash"`
	OnChain              bool   `json:"onChain" db:"on_chain"`
	KYC                  string `json:"kyc" db:"kyc"`
	ContractAudit        string `json:"contractAudit" db:"contract_audit"`
}

type StartupTeamMember struct {
	ComerID      uint64 `json:"comerID"`
	StartupID    uint64 `json:"startupID"`
	Position     string `json:"position"`
	Comer        string `json:"comer"`
	FollowedByMe bool   `json:"followedByMe"`
}

type Tag struct {
	Name     string `json:"name"`
	Category string `json:"category"`
	IsIndex  bool   `json:"isIndex"`
}

type Wallet struct {
	Address string `json:address`
}
